### ISSUE TITLE
Show initial velocity vectors when creating labs

### ISSUE THREAD

**Issue by AjaiKN** [WalnutProgramming/Physics-Engine-P5#17]
Suggested by @presssssure

**Comment by regexbuster** [comment]
Is this like an arrow coming out of the shape showing the initial vector?

**Comment by AjaiKN** [comment]
Yes

**Comment by AjaiKN** [comment]
For now, we can only show these while paused on the first frame, like we do for dragging objects:
<https://github.com/WalnutProgramming/Physics-Engine-P5/blob/master/experiment-src/start.js#L258-L260>.

Maybe later we'll make it so that there's a button to go to the first frame and pause ("visual editing mode" or something)

**Comment by regexbuster** [comment]
Alright, I think I got at least a rough draft. Let me add the first frame thing.

**Comment by regexbuster** [comment]
Branch: [https://github.com/WalnutProgramming/Physics-Engine-P5/tree/initial-velocity-arrow](url)
