### ISSUE TITLE
Don't show initial velocity arrow when there's zero initial velocity

### ISSUE THREAD

**Issue by AjaiKN** [WalnutProgramming/Physics-Engine-P5#23]
@regexBuster

**Comment by regexbuster** [comment]
I've fixed this let me push it. Still haven't gotten rendering on the arrow head because I've been busy.

**Comment by regexbuster** [comment]
Should be up if you check the branch. I'll try to get the rendering fixed tomorrow

**Comment by AjaiKN** [comment]
Thanks! I cherry-picked 39d0801763c7135cabe86620286f091fb6de49d5 into master.
