### ISSUE TITLE
Rendering issue with velocity vector arrows

### ISSUE THREAD

**Issue by AjaiKN** [WalnutProgramming/Physics-Engine-P5#24]
When I zoom in a lot or make the window size small, it looks great:

<img width="187" alt="image" src="https://user-images.githubusercontent.com/22969541/107082735-a1c09000-67c2-11eb-92a4-0916ab58d88b.png">

But at a normal window size, it looks like this on my computer:

<img width="128" alt="image" src="https://user-images.githubusercontent.com/22969541/107082797-b69d2380-67c2-11eb-8cd0-4f672fb2ffa6.png">

Here it is when I zoom out even further:

<img width="144" alt="image" src="https://user-images.githubusercontent.com/22969541/107082846-c74d9980-67c2-11eb-89f9-0cd53749b410.png">

Maybe it would be simpler to make the arrow head a filled triangle?

_Originally posted by @Aurelius333 in https://github.com/WalnutProgramming/Physics-Engine-P5/issues/20#issuecomment-774256949_

**Comment by AjaiKN** [comment]
@regexBuster

**Comment by AjaiKN** [comment]
We might also want to change the ratio so that the arrows are longer.

**Comment by regexbuster** [comment]
If I do increase the arrow size should I cap it at the canvas size? Or will the arrow be able to travel outside of the canvas?

**Comment by AjaiKN** [comment]
I increased the arrow size.

**Comment by regexbuster** [comment]
![image](https://user-images.githubusercontent.com/29523418/107696564-fb173c00-6c66-11eb-930a-92f72b3a8187.png)
Is this good? I can try to fill in the slight gap in the arrow head but haven't been successful yet.

**Comment by regexbuster** [comment]
![image](https://user-images.githubusercontent.com/29523418/107697737-75948b80-6c68-11eb-9ff8-d4ba7658b375.png)
Nevermind I split it up some things and it looks good now.
