### ISSUE TITLE
experiment previews on explore page

### ISSUE THREAD

**Issue by AjaiKN** [WalnutProgramming/Physics-Engine-P5#32]

**Comment by AjaiKN** [comment]
@regexBuster I'm going to split this into two separate issues since we might do things differently on the home and explore pages

**Comment by regexbuster** [comment]
alright. got all my stuff working again so that's a plus

**Comment by regexbuster** [comment]
the branch has been updated to have images appear. they look a little wild due to some cropping issues from the links doc. also, links are missing because <a> wasn't scaling nicely

edit: I lied the <a> tags are working now

**Comment by regexbuster** [comment]
always more work to be done. however, [this](https://github.com/WalnutProgramming/No-Lab-Physics/tree/explore-preview) branch now has 6 images that also have links to their labs

**Comment by AjaiKN** [comment]
I'll just merge it for now @regexBuster

**Comment by AjaiKN** [comment]
Never mind, not going to merge it right now

**Comment by regexbuster** [comment]
links are done and images look good. feel free to double check and merge. onwards to the milestone!

**Comment by AjaiKN** [comment]
merged
