### ISSUE TITLE
Do things in terms of delta time instead of frames

### ISSUE THREAD

**Issue by AjaiKN** [WalnutProgramming/Physics-Engine-P5#7]
Currently, we're doing everything in terms of **frames**. There's no real unit of time. This means that if we change the frame rate or someone's computer is too slow to render it at full speed, the simulation will slow down. Since it's important for us to be able to measure time for labs, it's good to make time consistent.

So what we'd like to do instead is something like this:

1. create a variable called `lastUpdated` and initialize it to `Date.now()` (the current time in milliseconds). Set it to `Date.now()` every frame after finding `deltaTime`.
2. Every frame, make a variable called `deltaTime` which is the difference between `Date.now()` and `lastUpdated` (i.e., then number of milliseconds since it was last updated)
3. Make all of the calculations be in terms of `deltaTime`. For example, we'd change this line: https://github.com/WalnutProgramming/Physics-Engine-P5/blob/6eb1576d80a47ddcf931bc84efd04e9f4ba696ae/script.js#L26 to be `this.vel.add(this.acc.copy().mult(deltaTime))`. 

You might want to share your code with us before you're done (maybe using a [draft pull request](https://github.blog/2019-02-14-introducing-draft-pull-requests/)) so that others can help, especially for step 3.

**Comment by JarnaChao09** [comment]
ok, question. We are working in a controlled environment where we are able to control the frame rate and subsequently time. If we did it with local time from the Date prototype, then we lose control of the time as it's not tied to the frame rate anymore, which would lead to complications when we pause and resume the simulation?
