### ISSUE TITLE
Create a ruler tool

### ISSUE THREAD

**Issue by AjaiKN** [WalnutProgramming/Physics-Engine-P5#8]
Create a ruler that people can use to measure distances.

**Comment by JarnaChao09** [comment]
Do we want the tool to have different units? or are we just going to do the metric system cuz who uses imperial anyway.

**Comment by regexBuster** [comment]
![ruler](https://user-images.githubusercontent.com/29523418/102541961-17d82e80-407f-11eb-8ee8-f151b853ccf3.jpg)

**Comment by regexbuster** [comment]
Thought I submitted my thing and wanted to come back to check up on it. I'm gonna go look in my external storage because I just reset my laptop and may no longer have it.

**Comment by regexbuster** [comment]
#9 
Assuming these links work I sent a pull request for the ruler thing.
edit: it did work
